### ISSUE TITLE
Add more games

### ISSUE THREAD

**Issue by jinx-vi-0** [TeekshaHarish/FunFusion#2]
@TeekshaHarish please assign me this issue under PHICSIT

**Comment by TeekshaHarish** [comment]
Which game do you want to add can you elaborate it a bit

**Comment by jinx-vi-0** [comment]
These are some, I have currently in mind:

1. SimonSays Game
2. Memory Card Game
3. Number Guessing Game
4. Snake Game
5. Word Guessing Game
6. Rock Paper Scissors Game
7. Work Scramble Game
8. Hangman

**Comment by TeekshaHarish** [comment]
Ok you can start working on this, assigning this issue to you.

**Comment by ZaidSunasra** [comment]
Can I also work on this - 
1) Connect 4
2) Wordle
3) Hand Cricket

**Comment by TeekshaHarish** [comment]
@ZaidSunasra okay you can also work on this

**Comment by ZaidSunasra** [comment]
Git Push gives error.   unable to access 'https://github.com/TeekshaHarish/FunFusion.git/': The requested URL returned error: 403
Cannot push. Please help

**Comment by AniketMishra23** [comment]
@TeekshaHarish Can I add a Ping Pong game?

**Comment by TeekshaHarish** [comment]
@AniketMishra23 can you explain the game in brief

**Comment by TeekshaHarish** [comment]
@AniketMishra23 yes you can add the ping pong game. Sry i was out of town so wasn't able to reply earlier

**Comment by TeekshaHarish** [comment]
@jinx-vi-0 are you still working on this issue?

**Comment by jinx-vi-0** [comment]
@TeekshaHarish I have created a pr. please check it and let me know the feedback.
