### ISSUE TITLE
Adding message for "TIE" in Tic Tac Toe

### ISSUE THREAD

**Issue by sneha9231** [TeekshaHarish/FunFusion#7]
![Screenshot 2024-03-26 024337](https://github.com/TeekshaHarish/FunFusion/assets/124514082/4a926de7-2191-4a01-a687-8a7cd1fb0878)
When this kind of situation arise there is no message can i add pop up saying " It's TIE; restart again "?

**Comment by TeekshaHarish** [comment]
Ok you can add that, assigning this issue to you.
