### ISSUE TITLE
add clear instruction in Simon Game

### ISSUE THREAD

**Issue by sneha9231** [TeekshaHarish/FunFusion#9]
There is no guide like  TIC TAC TOE on HOW TO PLAY

**Comment by TeekshaHarish** [comment]
You have written Simon game in the issue heading and Tic tac toe in description, which one are you referring to?

**Comment by sneha9231** [comment]
No, I meant, Like there were instructions on how to play "TIC TAC TOE" but there's no instructions for SIMON game, so its better to add instruction for that too.

**Comment by TeekshaHarish** [comment]
Yes you are right. You can add that to all the games which don't have how to play manual. Assigning this issue to you
